laborant@docker-01:~$ git clone https://github.com/ibnesayeed/linkextractor.git
cd linkextractor
git checkout demo
fatal: destination path 'linkextractor' already exists and is not an empty directory.
Switched to branch 'demo'
Your branch is up to date with 'origin/demo'.
laborant@docker-01:linkextractor$ git checkout step0
Switched to branch 'step0'
Your branch is up to date with 'origin/step0'.
laborant@docker-01:linkextractor$ cat linkextractor.py
#!/usr/bin/env python

import sys
import requests
from bs4 import BeautifulSoup

res = requests.get(sys.argv[-1])
soup = BeautifulSoup(res.text, "html.parser")
for link in soup.find_all("a"):
    print(link.get("href"))
laborant@docker-01:linkextractor$ ls -l linkextractor.py
-rw-rw-r-- 1 laborant laborant 220 Apr 18 21:13 linkextractor.py
laborant@docker-01:linkextractor$ python3 linkextractor.py
Traceback (most recent call last):
  File "/home/laborant/linkextractor/linkextractor.py", line 4, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
laborant@docker-01:linkextractor$ git checkout step1
branch 'step1' set up to track 'origin/step1'.
Switched to a new branch 'step1'
laborant@docker-01:linkextractor$ cat Dockerfile
FROM       python:3
LABEL      maintainer="Sawood Alam <@ibnesayeed>"

RUN        pip install beautifulsoup4
RUN        pip install requests

WORKDIR    /app
COPY       linkextractor.py /app/
RUN        chmod a+x linkextractor.py

ENTRYPOINT ["./linkextractor.py"]
laborant@docker-01:linkextractor$ docker image build -t linkextractor:step1 .
[+] Building 54.6s (11/11) FINISHED                                                                                                         docker:default
 => [internal] load build definition from Dockerfile                                                                                                  0.0s
 => => transferring dockerfile: 304B                                                                                                                  0.0s
 => [internal] load metadata for docker.io/library/python:3                                                                                           1.6s
 => [internal] load .dockerignore                                                                                                                     0.0s
 => => transferring context: 2B                                                                                                                       0.0s
 => [1/6] FROM docker.io/library/python:3@sha256:34dc8eb488136014caf530ec03a3a2403473a92d67a01a26256c365b5b2fc0d4                                    50.4s
 => => resolve docker.io/library/python:3@sha256:34dc8eb488136014caf530ec03a3a2403473a92d67a01a26256c365b5b2fc0d4                                     0.0s
 => => sha256:07d1b5af933d2dfc3d0dd509d6e20534825e4a537f7b006a6cb5b8e5a1f20905 24.01MB / 24.01MB                                                     12.7s
 => => sha256:34dc8eb488136014caf530ec03a3a2403473a92d67a01a26256c365b5b2fc0d4 10.04kB / 10.04kB                                                      0.0s
 => => sha256:f285e872b4525229679829f02db72786ab1a5022d2ab55d7d67ac3cc0becd790 6.26kB / 6.26kB                                                        0.0s
 => => sha256:1eb98adba0eb44a2e4facf9ca3626a4a66feedd0dd56d159cca90a35205744e7 64.40MB / 64.40MB                                                     38.8s
 => => sha256:416855cb95a0dd2b7149c91f4af88549def1af9c6c4fa9ab78404578bc97271d 2.32kB / 2.32kB                                                        0.0s
 => => sha256:23b7d26ef1d294256da0d70ce374277b9aab5ca683015073316005cb63d33849 48.49MB / 48.49MB                                                      6.6s
 => => extracting sha256:23b7d26ef1d294256da0d70ce374277b9aab5ca683015073316005cb63d33849                                                             0.7s
 => => sha256:b617a119f8a27982374d94ec6eb3738ae3d38d6fc2c34c865813926cf596a621 211.33MB / 211.33MB                                                   47.2s
 => => extracting sha256:07d1b5af933d2dfc3d0dd509d6e20534825e4a537f7b006a6cb5b8e5a1f20905                                                             0.2s
 => => sha256:171e1bee194953b20a247468c6e03a4d1f67ba21a8034398f4ce3e620880f3ef 6.16MB / 6.16MB                                                       18.2s
 => => sha256:e25cca11fd29c306a338d2d0397b465061f7a0c901916cc9ce7ecee3ed1e4823 27.37MB / 27.37MB                                                     32.3s
 => => sha256:739b86d2a77825bc516695d8b66c3db5b776f53a426387a2ff7acf8567d07049 251B / 251B                                                           34.1s
 => => extracting sha256:1eb98adba0eb44a2e4facf9ca3626a4a66feedd0dd56d159cca90a35205744e7                                                             1.0s
 => => extracting sha256:b617a119f8a27982374d94ec6eb3738ae3d38d6fc2c34c865813926cf596a621                                                             2.6s
 => => extracting sha256:171e1bee194953b20a247468c6e03a4d1f67ba21a8034398f4ce3e620880f3ef                                                             0.1s
 => => extracting sha256:e25cca11fd29c306a338d2d0397b465061f7a0c901916cc9ce7ecee3ed1e4823                                                             0.4s
 => => extracting sha256:739b86d2a77825bc516695d8b66c3db5b776f53a426387a2ff7acf8567d07049                                                             0.0s
 => [internal] load build context                                                                                                                     0.0s
 => => transferring context: 265B                                                                                                                     0.0s
 => [2/6] RUN        pip install beautifulsoup4                                                                                                       1.8s
 => [3/6] RUN        pip install requests                                                                                                             0.6s 
 => [4/6] WORKDIR    /app                                                                                                                             0.0s 
 => [5/6] COPY       linkextractor.py /app/                                                                                                           0.0s 
 => [6/6] RUN        chmod a+x linkextractor.py                                                                                                       0.1s
 => exporting to image                                                                                                                                0.0s
 => => exporting layers                                                                                                                               0.0s
 => => writing image sha256:2ba3ab90240af78b0b0870327e916e7a4ed74f36096d6b83defda2224d5a01aa                                                          0.0s
 => => naming to docker.io/library/linkextractor:step1                                                                                                0.0s
laborant@docker-01:linkextractor$ docker image ls
REPOSITORY      TAG       IMAGE ID       CREATED          SIZE
linkextractor   step1     2ba3ab90240a   19 seconds ago   1.03GB
laborant@docker-01:linkextractor$ docker container run -it --rm linkextractor:step1 http://example.com/
https://www.iana.org/domains/example
laborant@docker-01:linkextractor$ docker container run -it --rm linkextractor:step1 https://training.play-with-docker.com/
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
        conn,
    ...<10 lines>...
        **response_kw,
    )
  File "/usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py", line 488, in _make_request
    raise new_e
  File "/usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py", line 464, in _make_request
    self._validate_conn(conn)
    ~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py", line 1093, in _validate_conn
    conn.connect()
    ~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/urllib3/connection.py", line 741, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
        sock=sock,
    ...<14 lines>...
        assert_fingerprint=self.assert_fingerprint,
    )
  File "/usr/local/lib/python3.13/site-packages/urllib3/connection.py", line 920, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
        sock=sock,
    ...<8 lines>...
        tls_in_tls=tls_in_tls,
    )
  File "/usr/local/lib/python3.13/site-packages/urllib3/util/ssl_.py", line 480, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "/usr/local/lib/python3.13/site-packages/urllib3/util/ssl_.py", line 524, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/ssl.py", line 455, in wrap_socket
    return self.sslsocket_class._create(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sock=sock,
        ^^^^^^^^^^
    ...<5 lines>...
        session=session
        ^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/ssl.py", line 1076, in _create
    self.do_handshake()
    ~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/ssl.py", line 1372, in do_handshake
    self._sslobj.do_handshake()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
        method=request.method,
    ...<9 lines>...
        chunked=chunked,
    )
  File "/usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py", line 841, in urlopen
    retries = retries.increment(
        method, url, error=new_e, _pool=self, _stacktrace=sys.exc_info()[2]
    )
  File "/usr/local/lib/python3.13/site-packages/urllib3/util/retry.py", line 474, in increment
    raise reraise(type(error), error, _stacktrace)
          ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/urllib3/util/util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
        conn,
    ...<10 lines>...
        **response_kw,
    )
  File "/usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py", line 488, in _make_request
    raise new_e
  File "/usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py", line 464, in _make_request
    self._validate_conn(conn)
    ~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py", line 1093, in _validate_conn
    conn.connect()
    ~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/urllib3/connection.py", line 741, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
        sock=sock,
    ...<14 lines>...
        assert_fingerprint=self.assert_fingerprint,
    )
  File "/usr/local/lib/python3.13/site-packages/urllib3/connection.py", line 920, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
        sock=sock,
    ...<8 lines>...
        tls_in_tls=tls_in_tls,
    )
  File "/usr/local/lib/python3.13/site-packages/urllib3/util/ssl_.py", line 480, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "/usr/local/lib/python3.13/site-packages/urllib3/util/ssl_.py", line 524, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/ssl.py", line 455, in wrap_socket
    return self.sslsocket_class._create(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sock=sock,
        ^^^^^^^^^^
    ...<5 lines>...
        session=session
        ^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/ssl.py", line 1076, in _create
    self.do_handshake()
    ~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/ssl.py", line 1372, in do_handshake
    self._sslobj.do_handshake()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/./linkextractor.py", line 7, in <module>
    res = requests.get(sys.argv[-1])
  File "/usr/local/lib/python3.13/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.13/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/requests/adapters.py", line 682, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
laborant@docker-01:linkextractor$ ^C
laborant@docker-01:linkextractor$ RUN apt-get update && apt-get install -y ca-certificates
-bash: RUN: command not found
laborant@docker-01:linkextractor$ docker container run -it --rm linkextractor:step1 http://example.com
https://www.iana.org/domains/example
laborant@docker-01:linkextractor$ docker container run -it --rm --dns 8.8.8.8 linkextractor:step1 https://training.play-with-docker.com/
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
        conn,
    ...<10 lines>...
        **response_kw,
    )
  File "/usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py", line 488, in _make_request
    raise new_e
  File "/usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py", line 464, in _make_request
    self._validate_conn(conn)
    ~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py", line 1093, in _validate_conn
    conn.connect()
    ~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/urllib3/connection.py", line 741, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
        sock=sock,
    ...<14 lines>...
        assert_fingerprint=self.assert_fingerprint,
    )
  File "/usr/local/lib/python3.13/site-packages/urllib3/connection.py", line 920, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
        sock=sock,
    ...<8 lines>...
        tls_in_tls=tls_in_tls,
    )
  File "/usr/local/lib/python3.13/site-packages/urllib3/util/ssl_.py", line 480, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "/usr/local/lib/python3.13/site-packages/urllib3/util/ssl_.py", line 524, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/ssl.py", line 455, in wrap_socket
    return self.sslsocket_class._create(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sock=sock,
        ^^^^^^^^^^
    ...<5 lines>...
        session=session
        ^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/ssl.py", line 1076, in _create
    self.do_handshake()
    ~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/ssl.py", line 1372, in do_handshake
    self._sslobj.do_handshake()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
        method=request.method,
    ...<9 lines>...
        chunked=chunked,
    )
  File "/usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py", line 841, in urlopen
    retries = retries.increment(
        method, url, error=new_e, _pool=self, _stacktrace=sys.exc_info()[2]
    )
  File "/usr/local/lib/python3.13/site-packages/urllib3/util/retry.py", line 474, in increment
    raise reraise(type(error), error, _stacktrace)
          ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/urllib3/util/util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
        conn,
    ...<10 lines>...
        **response_kw,
    )
  File "/usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py", line 488, in _make_request
    raise new_e
  File "/usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py", line 464, in _make_request
    self._validate_conn(conn)
    ~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py", line 1093, in _validate_conn
    conn.connect()
    ~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/urllib3/connection.py", line 741, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
        sock=sock,
    ...<14 lines>...
        assert_fingerprint=self.assert_fingerprint,
    )
  File "/usr/local/lib/python3.13/site-packages/urllib3/connection.py", line 920, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
        sock=sock,
    ...<8 lines>...
        tls_in_tls=tls_in_tls,
    )
  File "/usr/local/lib/python3.13/site-packages/urllib3/util/ssl_.py", line 480, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "/usr/local/lib/python3.13/site-packages/urllib3/util/ssl_.py", line 524, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/ssl.py", line 455, in wrap_socket
    return self.sslsocket_class._create(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sock=sock,
        ^^^^^^^^^^
    ...<5 lines>...
        session=session
        ^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/ssl.py", line 1076, in _create
    self.do_handshake()
    ~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/ssl.py", line 1372, in do_handshake
    self._sslobj.do_handshake()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/./linkextractor.py", line 7, in <module>
    res = requests.get(sys.argv[-1])
  File "/usr/local/lib/python3.13/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.13/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/requests/adapters.py", line 682, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
laborant@docker-01:linkextractor$ docker container run -it --rm linkextractor:step1 http://training.play-with-docker.com/
laborant@docker-01:linkextractor$ docker container run -it --rm \
  -v /etc/ssl/certs:/etc/ssl/certs \
  linkextractor:step1 https://training.play-with-docker.com/
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
        conn,
    ...<10 lines>...
        **response_kw,
    )
  File "/usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py", line 488, in _make_request
    raise new_e
  File "/usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py", line 464, in _make_request
    self._validate_conn(conn)
    ~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py", line 1093, in _validate_conn
    conn.connect()
    ~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/urllib3/connection.py", line 741, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
        sock=sock,
    ...<14 lines>...
        assert_fingerprint=self.assert_fingerprint,
    )
  File "/usr/local/lib/python3.13/site-packages/urllib3/connection.py", line 920, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
        sock=sock,
    ...<8 lines>...
        tls_in_tls=tls_in_tls,
    )
  File "/usr/local/lib/python3.13/site-packages/urllib3/util/ssl_.py", line 480, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "/usr/local/lib/python3.13/site-packages/urllib3/util/ssl_.py", line 524, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/ssl.py", line 455, in wrap_socket
    return self.sslsocket_class._create(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sock=sock,
        ^^^^^^^^^^
    ...<5 lines>...
        session=session
        ^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/ssl.py", line 1076, in _create
    self.do_handshake()
    ~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/ssl.py", line 1372, in do_handshake
    self._sslobj.do_handshake()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
        method=request.method,
    ...<9 lines>...
        chunked=chunked,
    )
  File "/usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py", line 841, in urlopen
    retries = retries.increment(
        method, url, error=new_e, _pool=self, _stacktrace=sys.exc_info()[2]
    )
  File "/usr/local/lib/python3.13/site-packages/urllib3/util/retry.py", line 474, in increment
    raise reraise(type(error), error, _stacktrace)
          ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/urllib3/util/util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
        conn,
    ...<10 lines>...
        **response_kw,
    )
  File "/usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py", line 488, in _make_request
    raise new_e
  File "/usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py", line 464, in _make_request
    self._validate_conn(conn)
    ~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py", line 1093, in _validate_conn
    conn.connect()
    ~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/urllib3/connection.py", line 741, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
        sock=sock,
    ...<14 lines>...
        assert_fingerprint=self.assert_fingerprint,
    )
  File "/usr/local/lib/python3.13/site-packages/urllib3/connection.py", line 920, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
        sock=sock,
    ...<8 lines>...
        tls_in_tls=tls_in_tls,
    )
  File "/usr/local/lib/python3.13/site-packages/urllib3/util/ssl_.py", line 480, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "/usr/local/lib/python3.13/site-packages/urllib3/util/ssl_.py", line 524, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/ssl.py", line 455, in wrap_socket
    return self.sslsocket_class._create(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sock=sock,
        ^^^^^^^^^^
    ...<5 lines>...
        session=session
        ^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/ssl.py", line 1076, in _create
    self.do_handshake()
    ~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/ssl.py", line 1372, in do_handshake
    self._sslobj.do_handshake()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/./linkextractor.py", line 7, in <module>
    res = requests.get(sys.argv[-1])
  File "/usr/local/lib/python3.13/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.13/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/requests/adapters.py", line 682, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
laborant@docker-01:linkextractor$ docker container run -it --rm alpine sh -c "apk add curl && curl -v https://training.play-with-docker.com/"
Unable to find image 'alpine:latest' locally
latest: Pulling from library/alpine
f18232174bc9: Pull complete 
Digest: sha256:a8560b36e8b8210634f77d9f7f9efd7ffa463e380b75e2e74aff4511df3ef88c
Status: Downloaded newer image for alpine:latest
fetch https://dl-cdn.alpinelinux.org/alpine/v3.21/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.21/community/x86_64/APKINDEX.tar.gz
(1/9) Installing brotli-libs (1.1.0-r2)
(2/9) Installing c-ares (1.34.5-r0)
(3/9) Installing libunistring (1.2-r0)
(4/9) Installing libidn2 (2.3.7-r0)
(5/9) Installing nghttp2-libs (1.64.0-r0)
(6/9) Installing libpsl (0.21.5-r3)
(7/9) Installing zstd-libs (1.5.6-r2)
(8/9) Installing libcurl (8.12.1-r1)
(9/9) Installing curl (8.12.1-r1)
Executing busybox-1.37.0-r12.trigger
OK: 12 MiB in 24 packages
* Host training.play-with-docker.com:443 was resolved.
* IPv6: 2606:50c0:8003::153, 2606:50c0:8002::153, 2606:50c0:8001::153, 2606:50c0:8000::153
* IPv4: 185.199.110.153, 185.199.111.153, 185.199.109.153, 185.199.108.153
*   Trying [2606:50c0:8003::153]:443...
* Immediate connect fail for 2606:50c0:8003::153: Network unreachable
*   Trying [2606:50c0:8002::153]:443...
* Immediate connect fail for 2606:50c0:8002::153: Network unreachable
*   Trying [2606:50c0:8001::153]:443...
* Immediate connect fail for 2606:50c0:8001::153: Network unreachable
*   Trying [2606:50c0:8000::153]:443...
* Immediate connect fail for 2606:50c0:8000::153: Network unreachable
*   Trying 185.199.110.153:443...
* ALPN: curl offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/cert.pem
*  CApath: /etc/ssl/certs
* Recv failure: Connection reset by peer
* TLS connect error: error:00000000:lib(0)::reason(0)
* OpenSSL SSL_connect: Connection reset by peer in connection to training.play-with-docker.com:443 
* closing connection #0
curl: (35) Recv failure: Connection reset by peer
laborant@docker-01:linkextractor$ ping training.play-with-docker.com
ping: socktype: SOCK_RAW
ping: socket: Operation not permitted
ping: => missing cap_net_raw+p capability or setuid?
laborant@docker-01:linkextractor$ curl -I https://training.play-with-docker.com
curl: (35) Recv failure: Connection reset by peer
laborant@docker-01:linkextractor$ git checkout step2
branch 'step2' set up to track 'origin/step2'.
Switched to a new branch 'step2'
laborant@docker-01:linkextractor$ cat linkextractor.py
#!/usr/bin/env python

import sys
import requests
from bs4 import BeautifulSoup
from urllib.parse import urljoin

def extract_links(url):
    res = requests.get(url)
    soup = BeautifulSoup(res.text, "html.parser")
    base = url
    # TODO: Update base if a <base> element is present with the href attribute
    links = []
    for link in soup.find_all("a"):
        links.append({
            "text": " ".join(link.text.split()) or "[IMG]",
            "href": urljoin(base, link.get("href"))
        })
    return links

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("\nUsage:\n\t{} <URL>\n".format(sys.argv[0]))
        sys.exit(1)
    for link in extract_links(sys.argv[-1]):
        print("[{}]({})".format(link["text"], link["href"]))
laborant@docker-01:linkextractor$ docker image build -t linkextractor:step2 .
[+] Building 1.0s (11/11) FINISHED                                                                                                          docker:default
 => [internal] load build definition from Dockerfile                                                                                                  0.0s
 => => transferring dockerfile: 304B                                                                                                                  0.0s
 => [internal] load metadata for docker.io/library/python:3                                                                                           0.9s
 => [internal] load .dockerignore                                                                                                                     0.0s
 => => transferring context: 2B                                                                                                                       0.0s
 => [internal] load build context                                                                                                                     0.0s
 => => transferring context: 810B                                                                                                                     0.0s
 => [1/6] FROM docker.io/library/python:3@sha256:34dc8eb488136014caf530ec03a3a2403473a92d67a01a26256c365b5b2fc0d4                                     0.0s
 => CACHED [2/6] RUN        pip install beautifulsoup4                                                                                                0.0s
 => CACHED [3/6] RUN        pip install requests                                                                                                      0.0s
 => CACHED [4/6] WORKDIR    /app                                                                                                                      0.0s
 => [5/6] COPY       linkextractor.py /app/                                                                                                           0.0s
 => [6/6] RUN        chmod a+x linkextractor.py                                                                                                       0.1s
 => exporting to image                                                                                                                                0.0s
 => => exporting layers                                                                                                                               0.0s
 => => writing image sha256:fc0ef3b44d6f18d1704101006d440a389d6333a0d81e735051c44fdc92e3d5f0                                                          0.0s
 => => naming to docker.io/library/linkextractor:step2                                                                                                0.0s
laborant@docker-01:linkextractor$ docker image ls
REPOSITORY      TAG       IMAGE ID       CREATED          SIZE
linkextractor   step2     fc0ef3b44d6f   12 seconds ago   1.03GB
linkextractor   step1     2ba3ab90240a   16 minutes ago   1.03GB
alpine          latest    aded1e1a5b37   2 months ago     7.83MB
laborant@docker-01:linkextractor$ docker container run -it --rm linkextractor:step2 https://training.play-with-docker.com/
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
        conn,
    ...<10 lines>...
        **response_kw,
    )
  File "/usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py", line 488, in _make_request
    raise new_e
  File "/usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py", line 464, in _make_request
    self._validate_conn(conn)
    ~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py", line 1093, in _validate_conn
    conn.connect()
    ~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/urllib3/connection.py", line 741, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
        sock=sock,
    ...<14 lines>...
        assert_fingerprint=self.assert_fingerprint,
    )
  File "/usr/local/lib/python3.13/site-packages/urllib3/connection.py", line 920, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
        sock=sock,
    ...<8 lines>...
        tls_in_tls=tls_in_tls,
    )
  File "/usr/local/lib/python3.13/site-packages/urllib3/util/ssl_.py", line 480, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "/usr/local/lib/python3.13/site-packages/urllib3/util/ssl_.py", line 524, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/ssl.py", line 455, in wrap_socket
    return self.sslsocket_class._create(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sock=sock,
        ^^^^^^^^^^
    ...<5 lines>...
        session=session
        ^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/ssl.py", line 1076, in _create
    self.do_handshake()
    ~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/ssl.py", line 1372, in do_handshake
    self._sslobj.do_handshake()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
        method=request.method,
    ...<9 lines>...
        chunked=chunked,
    )
  File "/usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py", line 841, in urlopen
    retries = retries.increment(
        method, url, error=new_e, _pool=self, _stacktrace=sys.exc_info()[2]
    )
  File "/usr/local/lib/python3.13/site-packages/urllib3/util/retry.py", line 474, in increment
    raise reraise(type(error), error, _stacktrace)
          ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/urllib3/util/util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
        conn,
    ...<10 lines>...
        **response_kw,
    )
  File "/usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py", line 488, in _make_request
    raise new_e
  File "/usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py", line 464, in _make_request
    self._validate_conn(conn)
    ~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py", line 1093, in _validate_conn
    conn.connect()
    ~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/urllib3/connection.py", line 741, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
        sock=sock,
    ...<14 lines>...
        assert_fingerprint=self.assert_fingerprint,
    )
  File "/usr/local/lib/python3.13/site-packages/urllib3/connection.py", line 920, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
        sock=sock,
    ...<8 lines>...
        tls_in_tls=tls_in_tls,
    )
  File "/usr/local/lib/python3.13/site-packages/urllib3/util/ssl_.py", line 480, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "/usr/local/lib/python3.13/site-packages/urllib3/util/ssl_.py", line 524, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/ssl.py", line 455, in wrap_socket
    return self.sslsocket_class._create(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sock=sock,
        ^^^^^^^^^^
    ...<5 lines>...
        session=session
        ^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/ssl.py", line 1076, in _create
    self.do_handshake()
    ~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/ssl.py", line 1372, in do_handshake
    self._sslobj.do_handshake()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/./linkextractor.py", line 25, in <module>
    for link in extract_links(sys.argv[-1]):
                ~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/app/./linkextractor.py", line 9, in extract_links
    res = requests.get(url)
  File "/usr/local/lib/python3.13/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.13/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/requests/adapters.py", line 682, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
laborant@docker-01:linkextractor$ docker container run -it --rm linkextractor:step1 https://training.play-with-docker.com/
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
        conn,
    ...<10 lines>...
        **response_kw,
    )
  File "/usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py", line 488, in _make_request
    raise new_e
  File "/usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py", line 464, in _make_request
    self._validate_conn(conn)
    ~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py", line 1093, in _validate_conn
    conn.connect()
    ~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/urllib3/connection.py", line 741, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
        sock=sock,
    ...<14 lines>...
        assert_fingerprint=self.assert_fingerprint,
    )
  File "/usr/local/lib/python3.13/site-packages/urllib3/connection.py", line 920, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
        sock=sock,
    ...<8 lines>...
        tls_in_tls=tls_in_tls,
    )
  File "/usr/local/lib/python3.13/site-packages/urllib3/util/ssl_.py", line 480, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "/usr/local/lib/python3.13/site-packages/urllib3/util/ssl_.py", line 524, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/ssl.py", line 455, in wrap_socket
    return self.sslsocket_class._create(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sock=sock,
        ^^^^^^^^^^
    ...<5 lines>...
        session=session
        ^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/ssl.py", line 1076, in _create
    self.do_handshake()
    ~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/ssl.py", line 1372, in do_handshake
    self._sslobj.do_handshake()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
        method=request.method,
    ...<9 lines>...
        chunked=chunked,
    )
  File "/usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py", line 841, in urlopen
    retries = retries.increment(
        method, url, error=new_e, _pool=self, _stacktrace=sys.exc_info()[2]
    )
  File "/usr/local/lib/python3.13/site-packages/urllib3/util/retry.py", line 474, in increment
    raise reraise(type(error), error, _stacktrace)
          ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/urllib3/util/util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
        conn,
    ...<10 lines>...
        **response_kw,
    )
  File "/usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py", line 488, in _make_request
    raise new_e
  File "/usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py", line 464, in _make_request
    self._validate_conn(conn)
    ~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py", line 1093, in _validate_conn
    conn.connect()
    ~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/urllib3/connection.py", line 741, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
        sock=sock,
    ...<14 lines>...
        assert_fingerprint=self.assert_fingerprint,
    )
  File "/usr/local/lib/python3.13/site-packages/urllib3/connection.py", line 920, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
        sock=sock,
    ...<8 lines>...
        tls_in_tls=tls_in_tls,
    )
  File "/usr/local/lib/python3.13/site-packages/urllib3/util/ssl_.py", line 480, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "/usr/local/lib/python3.13/site-packages/urllib3/util/ssl_.py", line 524, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/ssl.py", line 455, in wrap_socket
    return self.sslsocket_class._create(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sock=sock,
        ^^^^^^^^^^
    ...<5 lines>...
        session=session
        ^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/ssl.py", line 1076, in _create
    self.do_handshake()
    ~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/ssl.py", line 1372, in do_handshake
    self._sslobj.do_handshake()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/./linkextractor.py", line 7, in <module>
    res = requests.get(sys.argv[-1])
  File "/usr/local/lib/python3.13/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.13/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/requests/adapters.py", line 682, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
laborant@docker-01:linkextractor$ docker container run -it --rm linkextractor:step1 http://training.play-with-docker.com/
laborant@docker-01:linkextractor$ git checkout step3
branch 'step3' set up to track 'origin/step3'.
Switched to a new branch 'step3'
laborant@docker-01:linkextractor$ cat Dockerfile
FROM       python:3
LABEL      maintainer="Sawood Alam <@ibnesayeed>"

WORKDIR    /app
COPY       requirements.txt /app/
RUN        pip install -r requirements.txt

COPY       *.py /app/
RUN        chmod a+x *.py

CMD        ["./main.py"]
laborant@docker-01:linkextractor$ cat main.py
#!/usr/bin/env python

from flask import Flask
from flask import request
from flask import jsonify
from linkextractor import extract_links

app = Flask(__name__)

@app.route("/")
def index():
    return "Usage: http://<hostname>[:<prt>]/api/<url>"

@app.route("/api/<path:url>")
def api(url):
    qs = request.query_string.decode("utf-8")
    if qs != "":
        url += "?" + qs
    links = extract_links(url)
    return jsonify(links)

app.run(host="0.0.0.0")
laborant@docker-01:linkextractor$ docker image build -t linkextractor:step3 .
[+] Building 2.2s (11/11) FINISHED                                                                                                          docker:default
 => [internal] load build definition from Dockerfile                                                                                                  0.0s
 => => transferring dockerfile: 278B                                                                                                                  0.0s
 => [internal] load metadata for docker.io/library/python:3                                                                                           0.4s
 => [internal] load .dockerignore                                                                                                                     0.0s
 => => transferring context: 2B                                                                                                                       0.0s
 => CACHED [1/6] FROM docker.io/library/python:3@sha256:34dc8eb488136014caf530ec03a3a2403473a92d67a01a26256c365b5b2fc0d4                              0.0s
 => [internal] load build context                                                                                                                     0.0s
 => => transferring context: 613B                                                                                                                     0.0s
 => [2/6] WORKDIR    /app                                                                                                                             0.0s
 => [3/6] COPY       requirements.txt /app/                                                                                                           0.0s
 => [4/6] RUN        pip install -r requirements.txt                                                                                                  1.6s
 => [5/6] COPY       *.py /app/                                                                                                                       0.0s 
 => [6/6] RUN        chmod a+x *.py                                                                                                                   0.1s 
 => exporting to image                                                                                                                                0.1s 
 => => exporting layers                                                                                                                               0.1s 
 => => writing image sha256:4ef6bd1cf23e92ebd1801583883e87b92b6e329343d4fc359cf931a4b35ee412                                                          0.0s 
 => => naming to docker.io/library/linkextractor:step3                                                                                                0.0s 
laborant@docker-01:linkextractor$ docker container run -d -p 5000:5000 --name=linkextractor linkextractor:step3
033f11ba34dd92055e2550cd54cb3b8ff0188fd745de629948ade750bb384956
laborant@docker-01:linkextractor$ docker container ls
CONTAINER ID   IMAGE                 COMMAND       CREATED         STATUS         PORTS                                         NAMES
033f11ba34dd   linkextractor:step3   "./main.py"   8 seconds ago   Up 7 seconds   0.0.0.0:5000->5000/tcp, [::]:5000->5000/tcp   linkextractor
laborant@docker-01:linkextractor$ curl -i http://localhost:5000/api/http://example.com/
HTTP/1.1 200 OK
Server: Werkzeug/3.1.3 Python/3.13.3
Date: Fri, 18 Apr 2025 21:36:36 GMT
Content-Type: application/json
Content-Length: 79
Connection: close

[{"href":"https://www.iana.org/domains/example","text":"More information..."}]
laborant@docker-01:linkextractor$ docker container logs linkextractor
 * Serving Flask app 'main'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.17.0.2:5000
Press CTRL+C to quit
172.17.0.1 - - [18/Apr/2025 21:36:36] "GET /api/http://example.com/ HTTP/1.1" 200 -
laborant@docker-01:linkextractor$ docker container rm -f linkextractor
linkextractor
laborant@docker-01:linkextractor$ git checkout step4
branch 'step4' set up to track 'origin/step4'.
Switched to a new branch 'step4'
laborant@docker-01:linkextractor$ cat docker-compose.yml
version: '3'

services:
  api:
    image: linkextractor-api:step4-python
    build: ./api
    ports:
      - "5000:5000"
  web:
    image: php:7-apache
    ports:
      - "80:80"
    environment:
      - API_ENDPOINT=http://api:5000/api/
    volumes:
      - ./www:/var/www/html
laborant@docker-01:linkextractor$ cat www/index.php
<!DOCTYPE html>

<?php
  $api_endpoint = $_ENV["API_ENDPOINT"] ?: "http://localhost:5000/api/";
  $url = "";
  if(isset($_GET["url"]) && $_GET["url"] != "") {
    $url = $_GET["url"];
    $json = @file_get_contents($api_endpoint . $url);
    if($json == false) {
      $err = "Something is wrong with the URL: " . $url;
    } else {
      $links = json_decode($json, true);
      $domains = [];
      foreach($links as $link) {
        array_push($domains, parse_url($link["href"], PHP_URL_HOST));
      }
      $domainct = @array_count_values($domains);
      arsort($domainct);
    }
  }
?>

<html>
  <head>
    <meta charset="utf-8">
    <title>Link Extractor</title>
    <style media="screen">
      html {
        background: #EAE7D6;
        font-family: sans-serif;
      }
      body {
        margin: 0;
      }
      h1 {
        padding: 10px;
        margin: 0 auto;
        color: #EAE7D6;
        max-width: 600px;
      }
      h1 a {
        text-decoration: none;
        color: #EAE7D6;
      }
      h2 {
        background: #082E41;
        color: #EAE7D6;
        margin: -10px;
        padding: 10px;
      }
      p {
        margin: 25px 5px 5px;
      }
      section {
        max-width: 600px;
        margin: 10px auto;
        padding: 10px;
        border: 1px solid #082E41;
      }
      div.header {
        background: #082E41;
        margin: 0;
      }
      div.footer {
        background: #082E41;
        margin: 0;
        padding: 5px;
      }
      .footer p {
        margin: 0 auto;
        max-width: 600px;
        color: #EAE7D6;
        text-align: center;
      }
      .footer p a {
        color: #24C2CB;
        text-decoration: none;
      }
      .error {
        color: #DA2536;
      }
      form {
        display: flex;
      }
      input {
        font-size: 20px;
        padding: 3px;
        height: 40px;
      }
      input.text {
        box-sizing:border-box;
        flex-grow: 1;
        border-color: #082E41;
      }
      input.button {
        width: 150px;
        background: #082E41;
        border-color: #082E41;
        color: #EAE7D6;
      }
      table {
        width: 100%;
        text-align: left;
        margin-top: 10px;
      }
      table th, table td {
        padding: 3px;
      }
      table th:last-child, table td:last-child {
        width: 70px;
        text-align: right;
      }
      table th {
        border-top: 1px solid #082E41;
        border-bottom: 1px solid #082E41;
      }
      table tr:last-child td {
        border-top: 1px solid #082E41;
        border-bottom: 1px solid #082E41;
      }
    </style>
  </head>
  <body>
    <div class="header">
      <h1><a href="/">Link Extractor</a></h1>
    </div>

    <section>
      <form action="/">
        <input class="text" type="text" name="url" placeholder="http://example.com/" value="<?php echo $url; ?>">
        <input class="button" type="submit" value="Extract Links">
      </form>
    </section>
    
    <?php if(isset($err)): ?>
      <section>
        <h2>Error</h2>
        <p class="error"><?php echo $err; ?></p>
      </section>
    <?php endif; ?>

    <?php if($url != "" && !isset($err)): ?>
      <section>
        <h2>Summary</h2>
        <p>
          <strong>Page:</strong> <?php echo "<a href=\"" . $url . "\">" . $url . "</a>"; ?>
        </p>
        <table>
          <tr>
            <th>Domain</th>
            <th># Links</th>
          </tr>
          <?php
            foreach($domainct as $key => $value) {
              echo "<tr>";
              echo "<td>" . $key . "</td>";
              echo "<td>" . $value . "</td>";
              echo "</tr>";
            }
          ?>
          <tr>
            <td><strong>Total</strong></td>
            <td><strong><?php echo count($links); ?></strong></td>
          </tr>
        </table>
      </section>

      <section>
        <h2>Links</h2>
        <ul>
        <?php
          foreach($links as $link) {
            echo "<li><a href=\"" . $link["href"] . "\">" . $link["text"] . "</a></li>";
          }
        ?>
        </ul>
      </section>
    <?php endif; ?>

    <div class="footer">
      <p><a href="https://github.com/ibnesayeed/linkextractor">Link Extractor</a> by <a href="https://twitter.com/ibnesayeed">@ibnesayeed</a> from
        <a href="https://ws-dl.cs.odu.edu/">WS-DL, ODU</a>
      </p>
    </div>
  </body>
</html>
laborant@docker-01:linkextractor$ docker-compose up -d --build
-bash: docker-compose: command not found
laborant@docker-01:linkextractor$ ^C
laborant@docker-01:linkextractor$ docker compose up -d --build
WARN[0000] /home/laborant/linkextractor/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 
[+] Running 14/14
 ✔ web Pulled                                                                                                                                        21.8s 
   ✔ a603fa5e3b41 Pull complete                                                                                                                       4.7s 
   ✔ c428f1a49423 Pull complete                                                                                                                       4.7s 
   ✔ 156740b07ef8 Pull complete                                                                                                                      19.1s 
   ✔ fb5a4c8af82f Pull complete                                                                                                                      19.1s 
   ✔ 25f85b498fd5 Pull complete                                                                                                                      19.4s 
   ✔ 9b233e420ac7 Pull complete                                                                                                                      19.4s 
   ✔ fe42347c4ecf Pull complete                                                                                                                      19.4s 
   ✔ d14eb2ed1e17 Pull complete                                                                                                                      19.5s 
   ✔ 66d98f73acb6 Pull complete                                                                                                                      19.5s 
   ✔ d2c43c5efbc8 Pull complete                                                                                                                      19.9s 
   ✔ ab590b48ea47 Pull complete                                                                                                                      19.9s 
   ✔ 80692ae2d067 Pull complete                                                                                                                      19.9s 
   ✔ 05e465aaa99a Pull complete                                                                                                                      20.1s 
Compose can now delegate builds to bake for better performance.
 To do so, set COMPOSE_BAKE=true.
[+] Building 0.8s (12/12) FINISHED                                                                                                          docker:default
 => [api internal] load build definition from Dockerfile                                                                                              0.0s
 => => transferring dockerfile: 278B                                                                                                                  0.0s
 => [api internal] load metadata for docker.io/library/python:3                                                                                       0.8s
 => [api internal] load .dockerignore                                                                                                                 0.0s
 => => transferring context: 2B                                                                                                                       0.0s
 => [api 1/6] FROM docker.io/library/python:3@sha256:34dc8eb488136014caf530ec03a3a2403473a92d67a01a26256c365b5b2fc0d4                                 0.0s
 => [api internal] load build context                                                                                                                 0.0s
 => => transferring context: 1.39kB                                                                                                                   0.0s
 => CACHED [api 2/6] WORKDIR    /app                                                                                                                  0.0s
 => CACHED [api 3/6] COPY       requirements.txt /app/                                                                                                0.0s
 => CACHED [api 4/6] RUN        pip install -r requirements.txt                                                                                       0.0s
 => CACHED [api 5/6] COPY       *.py /app/                                                                                                            0.0s
 => CACHED [api 6/6] RUN        chmod a+x *.py                                                                                                        0.0s
 => [api] exporting to image                                                                                                                          0.0s
 => => exporting layers                                                                                                                               0.0s
 => => writing image sha256:9f92592fce9d1188cfac08398d52f0a64e113fa5964a91b856bec242817ae8b9                                                          0.0s
 => => naming to docker.io/library/linkextractor-api:step4-python                                                                                     0.0s
 => [api] resolving provenance for metadata file                                                                                                      0.0s
[+] Running 4/4
 ✔ api                            Built                                                                                                               0.0s 
 ✔ Network linkextractor_default  Created                                                                                                             0.0s 
 ✔ Container linkextractor-api-1  Started                                                                                                             1.4s 
 ✔ Container linkextractor-web-1  Started                                                                                                             1.4s 
laborant@docker-01:linkextractor$ docker container ls
CONTAINER ID   IMAGE                            COMMAND                  CREATED          STATUS          PORTS                                         NAMES
c5741e760937   php:7-apache                     "docker-php-entrypoi…"   24 seconds ago   Up 22 seconds   0.0.0.0:80->80/tcp, [::]:80->80/tcp           linkextractor-web-1
5c62d4592aaf   linkextractor-api:step4-python   "./main.py"              24 seconds ago   Up 22 seconds   0.0.0.0:5000->5000/tcp, [::]:5000->5000/tcp   linkextractor-api-1
laborant@docker-01:linkextractor$ curl -i http://localhost:5000/api/http://example.com/
HTTP/1.1 200 OK
Server: Werkzeug/3.1.3 Python/3.13.3
Date: Fri, 18 Apr 2025 21:40:51 GMT
Content-Type: application/json
Content-Length: 79
Connection: close

[{"href":"https://www.iana.org/domains/example","text":"More information..."}]
laborant@docker-01:linkextractor$ sed -i 's/Link Extractor/Super Link Extractor/g' www/index.php
laborant@docker-01:linkextractor$ git reset --hard
HEAD is now at 2a3ec3e Synchronize branch step4
laborant@docker-01:linkextractor$ docker-compose down
-bash: docker-compose: command not found
laborant@docker-01:linkextractor$ docker compose down
WARN[0000] /home/laborant/linkextractor/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 
[+] Running 3/3
 ✔ Container linkextractor-web-1  Removed                                                                                                             1.1s 
 ✔ Container linkextractor-api-1  Removed                                                                                                            10.1s 
 ✔ Network linkextractor_default  Removed                                                                                                             0.1s 
laborant@docker-01:linkextractor$ git checkout step5
branch 'step5' set up to track 'origin/step5'.
Switched to a new branch 'step5'
laborant@docker-01:linkextractor$ cat www/Dockerfile
FROM       php:7-apache
LABEL      maintainer="Sawood Alam <@ibnesayeed>"

ENV        API_ENDPOINT="http://localhost:5000/api/"

COPY       . /var/www/html/
laborant@docker-01:linkextractor$ cat api/main.py
#!/usr/bin/env python

import os
import json
import redis
from flask import Flask
from flask import request
from linkextractor import extract_links

app = Flask(__name__)
redis_conn = redis.from_url(os.getenv("REDIS_URL", "redis://localhost:6379"))

@app.route("/")
def index():
    return "Usage: http://<hostname>[:<prt>]/api/<url>"

@app.route("/api/<path:url>")
def api(url):
    qs = request.query_string.decode("utf-8")
    if qs != "":
        url += "?" + qs

    jsonlinks = redis_conn.get(url)
    if not jsonlinks:
        links = extract_links(url)
        jsonlinks = json.dumps(links, indent=2)
        redis_conn.set(url, jsonlinks)

    response = app.response_class(
        status=200,
        mimetype="application/json",
        response=jsonlinks
    )

    return response

app.run(host="0.0.0.0")
laborant@docker-01:linkextractor$ cat docker-compose.yml
version: '3'

services:
  api:
    image: linkextractor-api:step5-python
    build: ./api
    ports:
      - "5000:5000"
    environment:
      - REDIS_URL=redis://redis:6379
  web:
    image: linkextractor-web:step5-php
    build: ./www
    ports:
      - "80:80"
    environment:
      - API_ENDPOINT=http://api:5000/api/
  redis:
    image: redis
laborant@docker-01:linkextractor$ docker compose up -d --build
WARN[0000] /home/laborant/linkextractor/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 
[+] Running 9/9
 ✔ redis Pulled                                                                                                                                       7.0s 
   ✔ 8a628cdd7ccc Pull complete                                                                                                                       3.8s 
   ✔ 3ff860482ac5 Pull complete                                                                                                                       3.8s 
   ✔ 811af041d785 Pull complete                                                                                                                       3.8s 
   ✔ a7e27cf18de4 Pull complete                                                                                                                       3.8s 
   ✔ 8ae1ad8ce35e Pull complete                                                                                                                       5.2s 
   ✔ 759939a29cb5 Pull complete                                                                                                                       5.2s 
   ✔ 4f4fb700ef54 Pull complete                                                                                                                       5.2s 
   ✔ cbb99c664e48 Pull complete                                                                                                                       5.2s 
Compose can now delegate builds to bake for better performance.
 To do so, set COMPOSE_BAKE=true.
[+] Building 3.0s (20/20) FINISHED                                                                                                          docker:default
 => [web internal] load build definition from Dockerfile                                                                                              0.0s
 => => transferring dockerfile: 196B                                                                                                                  0.0s
 => [api internal] load build definition from Dockerfile                                                                                              0.0s
 => => transferring dockerfile: 325B                                                                                                                  0.0s
 => [api internal] load metadata for docker.io/library/python:3                                                                                       1.1s
 => [web internal] load metadata for docker.io/library/php:7-apache                                                                                   0.0s
 => [web internal] load .dockerignore                                                                                                                 0.0s
 => => transferring context: 2B                                                                                                                       0.0s
 => [web internal] load build context                                                                                                                 0.0s
 => => transferring context: 4.63kB                                                                                                                   0.0s
 => [web 1/2] FROM docker.io/library/php:7-apache                                                                                                     0.0s
 => [web 2/2] COPY       . /var/www/html/                                                                                                             0.6s
 => [web] exporting to image                                                                                                                          0.0s
 => => exporting layers                                                                                                                               0.0s
 => => writing image sha256:4423341f707c89a2a8a7a898e6fd5b6e11156aca788fbd4af253c8e9407de42f                                                          0.0s
 => => naming to docker.io/library/linkextractor-web:step5-php                                                                                        0.0s
 => [web] resolving provenance for metadata file                                                                                                      0.0s
 => [api internal] load .dockerignore                                                                                                                 0.0s
 => => transferring context: 2B                                                                                                                       0.0s
 => [api 1/6] FROM docker.io/library/python:3@sha256:34dc8eb488136014caf530ec03a3a2403473a92d67a01a26256c365b5b2fc0d4                                 0.0s
 => [api internal] load build context                                                                                                                 0.0s
 => => transferring context: 977B                                                                                                                     0.0s
 => CACHED [api 2/6] WORKDIR    /app                                                                                                                  0.0s
 => [api 3/6] COPY       requirements.txt /app/                                                                                                       0.0s
 => [api 4/6] RUN        pip install -r requirements.txt                                                                                              1.7s
 => [api 5/6] COPY       *.py /app/                                                                                                                   0.0s
 => [api 6/6] RUN        chmod a+x *.py                                                                                                               0.1s 
 => [api] exporting to image                                                                                                                          0.1s 
 => => exporting layers                                                                                                                               0.1s 
 => => writing image sha256:3412f2aa71cdaeb9e3475aa4b972095a30dabc9fbd2f63bf1bb685404b246a89                                                          0.0s 
 => => naming to docker.io/library/linkextractor-api:step5-python                                                                                     0.0s
 => [api] resolving provenance for metadata file                                                                                                      0.0s
[+] Running 6/6
 ✔ api                              Built                                                                                                             0.0s 
 ✔ web                              Built                                                                                                             0.0s 
 ✔ Network linkextractor_default    Created                                                                                                           0.0s 
 ✔ Container linkextractor-api-1    Started                                                                                                           0.1s 
 ✔ Container linkextractor-web-1    Started                                                                                                           0.2s 
 ✔ Container linkextractor-redis-1  Started                                                                                                           0.1s 
laborant@docker-01:linkextractor$ docker compose exec redis redis-cli monitor
WARN[0000] /home/laborant/linkextractor/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 
OK

OK
^C
laborant@docker-01:linkextractor$ docker compose exec redis redis-cli monitor
WARN[0000] /home/laborant/linkextractor/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 
OK
^C
laborant@docker-01:linkextractor$ sed -i 's/Link Extractor/Super Link Extractor/g' www/index.php
laborant@docker-01:linkextractor$ git reset --hard
HEAD is now at 3dbb7eb Synchronize branch step5
laborant@docker-01:linkextractor$ docker compose down
WARN[0000] /home/laborant/linkextractor/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 
[+] Running 4/4
 ✔ Container linkextractor-api-1    Removed                                                                                                          10.2s 
 ✔ Container linkextractor-web-1    Removed                                                                                                           1.1s 
 ✔ Container linkextractor-redis-1  Removed                                                                                                           0.2s 
 ✔ Network linkextractor_default    Removed                                                                                                           0.1s 
laborant@docker-01:linkextractor$ git checkout step6
branch 'step6' set up to track 'origin/step6'.
Switched to a new branch 'step6'
laborant@docker-01:linkextractor$ cat api/linkextractor.rb
#!/usr/bin/env ruby
# encoding: utf-8

require "sinatra"
require "open-uri"
require "uri"
require "nokogiri"
require "json"
require "redis"

set :protection, :except=>:path_traversal

redis = Redis.new(url: ENV["REDIS_URL"] || "redis://localhost:6379")

Dir.mkdir("logs") unless Dir.exist?("logs")
cache_log = File.new("logs/extraction.log", "a")

get "/" do
  "Usage: http://<hostname>[:<prt>]/api/<url>"
end

get "/api/*" do
  url = [params['splat'].first, request.query_string].reject(&:empty?).join("?")
  cache_status = "HIT"
  jsonlinks = redis.get(url)
  if jsonlinks.nil?
    cache_status = "MISS"
    jsonlinks = JSON.pretty_generate(extract_links(url))
    redis.set(url, jsonlinks)
  end

  cache_log.puts "#{Time.now.to_i}\t#{cache_status}\t#{url}"

  status 200
  headers "content-type" => "application/json"
  body jsonlinks
end

def extract_links(url)
  links = []
  doc = Nokogiri::HTML(open(url))
  doc.css("a").each do |link|
    text = link.text.strip.split.join(" ")
    begin
      links.push({
        text: text.empty? ? "[IMG]" : text,
        href: URI.join(url, link["href"])
      })
    rescue
    end
  end
  links
end
laborant@docker-01:linkextractor$ cat api/Dockerfile
FROM       ruby:2.6
LABEL      maintainer="Sawood Alam <@ibnesayeed>"

ENV        LANG C.UTF-8
ENV        REDIS_URL="redis://localhost:6379"

WORKDIR    /app
COPY       Gemfile /app/
RUN        bundle install

COPY       linkextractor.rb /app/
RUN        chmod a+x linkextractor.rb

CMD        ["./linkextractor.rb", "-o", "0.0.0.0"]
laborant@docker-01:linkextractor$ cat docker-compose.yml
version: '3'

services:
  api:
    image: linkextractor-api:step6-ruby
    build: ./api
    ports:
      - "4567:4567"
    environment:
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./logs:/app/logs
  web:
    image: linkextractor-web:step6-php
    build: ./www
    ports:
      - "80:80"
    environment:
      - API_ENDPOINT=http://api:4567/api/
  redis:
    image: redis
laborant@docker-01:linkextractor$ docker compose up -d --build
WARN[0000] /home/laborant/linkextractor/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 
Compose can now delegate builds to bake for better performance.
 To do so, set COMPOSE_BAKE=true.
[+] Building 50.9s (16/18)                                                                                                                  docker:default
 => [web internal] load build definition from Dockerfile                                                                                              0.0s
 => => transferring dockerfile: 140B                                                                                                                  0.0s
 => [web internal] load metadata for docker.io/library/php:7-apache                                                                                   0.0s
 => [web internal] load .dockerignore                                                                                                                 0.0s
 => => transferring context: 2B                                                                                                                       0.0s
 => [api internal] load build definition from Dockerfile                                                                                              0.0s
 => => transferring dockerfile: 373B                                                                                                                  0.0s
 => [web internal] load build context                                                                                                                 0.0s
 => => transferring context: 4.57kB                                                                                                                   0.0s
 => CACHED [web 1/2] FROM docker.io/library/php:7-apache                                                                                              0.0s
 => [api internal] load metadata for docker.io/library/ruby:2.6                                                                                       1.3s
 => [web 2/2] COPY       . /var/www/html/                                                                                                             0.0s
 => [web] exporting to image                                                                                                                          0.0s
 => => exporting layers                                                                                                                               0.0s
 => => writing image sha256:c3eca6cbbd981f5e66926516eb16ac5dd0ef87b18021dcddab557670842c3b2e                                                          0.0s
 => => naming to docker.io/library/linkextractor-web:step6-php                                                                                        0.0s
 => [web] resolving provenance for metadata file                                                                                                      0.0s
 => [api internal] load .dockerignore                                                                                                                 0.0s
 => => transferring context: 2B                                                                                                                       0.0s
 => [api 1/6] FROM docker.io/library/ruby:2.6@sha256:a79c8ddb7f3d3748427e2d3a45dcae6d42f1d80d9ae3b98959b3a27b220bf434                                46.3s
 => => resolve docker.io/library/ruby:2.6@sha256:a79c8ddb7f3d3748427e2d3a45dcae6d42f1d80d9ae3b98959b3a27b220bf434                                     0.0s
 => => sha256:771a810704167e55da8a19970c5dfa6eb795dfee32547adffa29ea72703f7243 2.00kB / 2.00kB                                                        0.0s
 => => sha256:b71cca836fff8e4f14f8575e25a157f3e253bcd1a039432f4980728c846603f7 7.29kB / 7.29kB                                                        0.0s
 => => sha256:6aefca2dc61dcbcd268b8a9861e552f9cdb69e57242faec64ac120d2355a9c1a 54.94MB / 54.94MB                                                     11.1s
 => => sha256:a79c8ddb7f3d3748427e2d3a45dcae6d42f1d80d9ae3b98959b3a27b220bf434 1.86kB / 1.86kB                                                        0.0s
 => => sha256:c357e2c68cb3bf1e98dcb3eb6ceb16837253db71535921d6993c594588bffe04 10.87MB / 10.87MB                                                     11.9s
 => => sha256:967757d5652770cfa81b6cc7577d65e06d336173da116d1fb5b2d349d5d44127 5.16MB / 5.16MB                                                        1.4s
 => => sha256:c766e27afb21eddf9ab3e4349700ebe697c32a4c6ada6af4f08282277a291a28 54.58MB / 54.58MB                                                     18.4s
 => => extracting sha256:6aefca2dc61dcbcd268b8a9861e552f9cdb69e57242faec64ac120d2355a9c1a                                                             0.8s
 => => sha256:32a180f5cf85702e7680719c40c39c07972b1176355df5a621de9eb87ad07ce2 196.70MB / 196.70MB                                                   42.4s
 => => sha256:ac0f2cbcefb35e4530dc103f764c05af8ab6b8a9de164b36093fa9db8b375e35 200B / 200B                                                           12.8s
 => => extracting sha256:967757d5652770cfa81b6cc7577d65e06d336173da116d1fb5b2d349d5d44127                                                             0.1s
 => => extracting sha256:c357e2c68cb3bf1e98dcb3eb6ceb16837253db71535921d6993c594588bffe04                                                             0.1s
 => => sha256:9c8a39a9be946d172ec9cb947630763435952f1e6477b60474636a975b4c8e8f 21.68MB / 21.68MB                                                     28.5s
 => => sha256:3fdd4263cfa33c03da28ce7a8157b2861fc47ac5e335e1f0e79f643d3dc073c9 175B / 175B                                                           20.1s
 => => extracting sha256:c766e27afb21eddf9ab3e4349700ebe697c32a4c6ada6af4f08282277a291a28                                                             0.9s
 => => extracting sha256:32a180f5cf85702e7680719c40c39c07972b1176355df5a621de9eb87ad07ce2                                                             2.3s
 => => extracting sha256:ac0f2cbcefb35e4530dc103f764c05af8ab6b8a9de164b36093fa9db8b375e35                                                             0.0s
 => => extracting sha256:9c8a39a9be946d172ec9cb947630763435952f1e6477b60474636a975b4c8e8f                                                             0.2s
 => => extracting sha256:3fdd4263cfa33c03da28ce7a8157b2861fc47ac5e335e1f0e79f643d3dc073c9                                                             0.0s
 => [api internal] load build context                                                                                                                 0.0s
 => => transferring context: 1.30kB                                                                                                                   0.0s
 => [api 2/6] WORKDIR    /app                                                                                                                         2.8s
 => [api 3/6] COPY       Gemfile /app/                                                                                                                0.1s
 => ERROR [api 4/6] RUN        bundle install                                                                                                         0.3s
------
 > [api 4/6] RUN        bundle install:
0.244 Fetching source index from https://rubygems.org/
0.246 
0.246 Retrying fetcher due to error (2/4): Bundler::HTTPError Could not fetch specs from https://rubygems.org/
0.247 Retrying fetcher due to error (3/4): Bundler::HTTPError Could not fetch specs from https://rubygems.org/
0.248 Retrying fetcher due to error (4/4): Bundler::HTTPError Could not fetch specs from https://rubygems.org/
0.252 Could not fetch specs from https://rubygems.org/
------
failed to solve: process "/bin/sh -c bundle install" did not complete successfully: exit code: 17
laborant@docker-01:linkextractor$ docker compose up -d --build
WARN[0000] /home/laborant/linkextractor/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 
Compose can now delegate builds to bake for better performance.
 To do so, set COMPOSE_BAKE=true.
[+] Building 0.7s (16/18)                                                                                                                   docker:default
 => [web internal] load build definition from Dockerfile                                                                                              0.0s
 => => transferring dockerfile: 140B                                                                                                                  0.0s
 => [api internal] load build definition from Dockerfile                                                                                              0.0s
 => => transferring dockerfile: 373B                                                                                                                  0.0s
 => [web internal] load metadata for docker.io/library/php:7-apache                                                                                   0.0s
 => [web internal] load .dockerignore                                                                                                                 0.0s
 => => transferring context: 2B                                                                                                                       0.0s
 => [api internal] load metadata for docker.io/library/ruby:2.6                                                                                       0.4s
 => [web internal] load build context                                                                                                                 0.0s
 => => transferring context: 60B                                                                                                                      0.0s
 => [web 1/2] FROM docker.io/library/php:7-apache                                                                                                     0.0s
 => CACHED [web 2/2] COPY       . /var/www/html/                                                                                                      0.0s
 => [web] exporting to image                                                                                                                          0.0s
 => => exporting layers                                                                                                                               0.0s
 => => writing image sha256:c3eca6cbbd981f5e66926516eb16ac5dd0ef87b18021dcddab557670842c3b2e                                                          0.0s
 => => naming to docker.io/library/linkextractor-web:step6-php                                                                                        0.0s
 => [web] resolving provenance for metadata file                                                                                                      0.0s
 => [api internal] load .dockerignore                                                                                                                 0.0s
 => => transferring context: 2B                                                                                                                       0.0s
 => [api 1/6] FROM docker.io/library/ruby:2.6@sha256:a79c8ddb7f3d3748427e2d3a45dcae6d42f1d80d9ae3b98959b3a27b220bf434                                 0.0s
 => [api internal] load build context                                                                                                                 0.0s
 => => transferring context: 64B                                                                                                                      0.0s
 => CACHED [api 2/6] WORKDIR    /app                                                                                                                  0.0s
 => CACHED [api 3/6] COPY       Gemfile /app/                                                                                                         0.0s
 => ERROR [api 4/6] RUN        bundle install                                                                                                         0.3s
------                                                                                                                                                     
 > [api 4/6] RUN        bundle install:
0.245 Fetching source index from https://rubygems.org/
0.248 
0.248 Retrying fetcher due to error (2/4): Bundler::HTTPError Could not fetch specs from https://rubygems.org/
0.249 Retrying fetcher due to error (3/4): Bundler::HTTPError Could not fetch specs from https://rubygems.org/
0.251 Retrying fetcher due to error (4/4): Bundler::HTTPError Could not fetch specs from https://rubygems.org/
0.254 Could not fetch specs from https://rubygems.org/
------
failed to solve: process "/bin/sh -c bundle install" did not complete successfully: exit code: 17
laborant@docker-01:linkextractor$ curl -i http://localhost:4567/api/http://example.com/
curl: (7) Failed to connect to localhost port 4567 after 0 ms: Couldn't connect to server